apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: tatyana8/job4j_passport_client
          env:
            - name: SERVER_PASSPORT_URL
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: SERVER_PASSPORT_URL
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service

metadata:
  name: client-service
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
#      nodePort: 32102

