apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: tatyana8/job4j_passport_server
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgresdb-configmap
                  key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: passport-service
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 32100

